services:
  frontend:
    build: .
    image: cargo-from-china 
    ports:
      - "3000:5173" 
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true