services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user_service
    ports:
      - "5434:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-db-2:
    image: postgres:15
    container_name: postgres-db-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_2
      POSTGRES_DB: case_service
    ports:
      - "5433:5432"  # Different host port
    networks:
      - my-network
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3007:3000"
    networks:
      - my-network
    depends_on:
      - prometheus

  gateway:
    build:
      context: ./services/gateway_service
    env_file:
      - ./services/gateway_service/.env
    ports:
      - "8009:8000"
    depends_on:
      - user-service
      - case-service
      - currency-service
      - calc-service
    networks:
      - my-network

  user-service:
    build:
      context: ./services/users_service
    container_name: users-service
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:secret@postgres-db:5432/user_service"
    depends_on:
      - postgres-db
    networks:
      - my-network
    volumes:
      - ./services/users_service:/app

  case-service:
    build:
      context: ./services/case_service
    container_name: case-service
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:secret_2@postgres-db-2:5432/case_service"
    ports:
      - "8006:8006"
    depends_on:
      - postgres-db-2
    networks:
      - my-network
    volumes:
      - ./services/case_service:/app
      - ./uploads:/app/uploads

  currency-service:
    build:
      context: ./services/currency_service
    container_name: currency-service
    ports:
      - "8003:8003"
    networks:
      - my-network
    environment:
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./services/currency_service:/app

  calc-service:
    build:
      context: ./services/calc_service
    container_name: calc-service
    ports:
      - "8004:8004"
    networks:
      - my-network
    volumes:
      - ./services/calc_service:/app


  worker:
    build:
      context: ./services/users_service  # или путь к корню с celery_app.py
    container_name: celery-worker
    command: celery -A services.users_service.celery_app.celery worker --loglevel=info
    environment:
      # Пробрасываем переменные для доступа к Redis и БД
      DATABASE_URL: "postgresql+asyncpg://postgres:secret@postgres-db:5432/user_service"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres-db
    networks:
      - my-network

    # === Celery beat (планировщик) ===
  beat:
    build:
      context: ./services/users_service
    container_name: celery-beat
    command: celery -A services.users_service.celery_app.celery beat --loglevel=info
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:secret@postgres-db:5432/user_service"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres-db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local



